services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: bharat
      POSTGRES_PASSWORD: bharat
      POSTGRES_DB: bharat_rail
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  pgdata:
