import { Router } from "express";
import { planned } from "../../lib/http.js";

const router = Router();

const plannedRoutes = [
  ["get", "/users/preferences"],
  ["patch", "/users/preferences"],
  ["get", "/users/saved-routes"],
  ["post", "/users/saved-routes"],
  ["delete", "/users/saved-routes/:id"],
  ["get", "/stations/popular"],
  ["get", "/trains/:trainNumber/schedule"],
  ["get", "/availability/:trainNumber"],
  ["get", "/availability/calendar"],
  ["get", "/fare/:trainNumber"],
  ["get", "/seats/layout/:trainNumber/:coach"],
  ["get", "/passengers"],
  ["post", "/passengers"],
  ["patch", "/passengers/:id"],
  ["delete", "/passengers/:id"],
  ["post", "/payments/refund"],
  ["get", "/pnr/:pnrNumber/chart"],
  ["get", "/tickets/:id/download"],
  ["get", "/tickets/:id/qr"],
  ["post", "/tdr/file"],
  ["get", "/tdr/:id/status"],
  ["get", "/waitlist/:pnrNumber/prediction"],
  ["get", "/waitlist/:trainNumber/position"],
  ["post", "/waitlist/notify-on-confirm"],
  ["get", "/live-status/:trainNumber/eta/:stationCode"],
  ["get", "/trains/:trainNumber/delay-history"],
  ["post", "/meals/order"],
  ["get", "/meals/orders/:id"],
  ["get", "/retiring-rooms"],
  ["post", "/retiring-rooms/book"],
  ["get", "/lounges"],
  ["get", "/notifications"],
  ["patch", "/notifications/read"],
  ["post", "/notifications/subscribe"],
  ["get", "/notifications/preferences"],
  ["put", "/notifications/preferences"],
  ["post", "/agents/register"],
  ["get", "/agents/profile"],
  ["post", "/agents/bookings"],
  ["get", "/agents/commissions"],
  ["get", "/agents/wallet"],
  ["post", "/agents/wallet/recharge"],
  ["get", "/agents/customers"],
  ["post", "/agents/customers"],
  ["get", "/offers"],
  ["post", "/offers/apply"],
  ["get", "/loyalty"],
  ["post", "/loyalty/redeem"],
  ["get", "/insurance/plans"],
  ["post", "/insurance/select"],
  ["get", "/admin/bookings"],
  ["get", "/admin/users"],
  ["post", "/admin/trains"],
  ["post", "/admin/quota-management"],
  ["get", "/admin/fraud-flags"],
  ["get", "/reports/revenue"],
  ["get", "/reports/bookings"],
  ["get", "/reports/popular-routes"],
  ["get", "/analytics/dashboard"],
  ["get", "/analytics/occupancy"],
  ["post", "/support/tickets"],
  ["post", "/feedback"],
  ["get", "/audit/logs"],
  ["get", "/audit/bookings"],
  ["get", "/system/status"],
  ["get", "/system/server-time"]
];

for (const [method, path] of plannedRoutes) {
  router[method](path, planned);
}

export default router;
